### ISSUE TITLE
No Static method AnimatedContent(ljava/lang/Object....

### ISSUE THREAD

**Issue by gastsail** [Tlaster/PreCompose#105]
I'm having an issue with 1.4.3 version of the library, suddenly it stopped working, it was working before and it works on iOS but not on Android. here is the stacktrace

```
java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Ljava/lang/String;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~1cPNQhZr_sEBYqeDK1_h0g==/com.myapplication.MyApplication-iVATTglp6ceQIOGY27BisQ==/base.apk)
                                                                                                    	at moe.tlaster.precompose.navigation.NavHostKt.NavHost(NavHost.kt:135)
                                                                                                    	at navigation.NavigatorKt.Navigation(Navigator.kt:19)
                                                                                                    	at ComposableSingletons$AppKt$lambda-3$1$2.invoke(App.kt:76)
                                                                                                    	at ComposableSingletons$AppKt$lambda-3$1$2.invoke(App.kt:74)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
```

The code with the problem is at the NavHost implementation

```
  Box(modifier) {
        val currentSceneEntry by navigator.stackManager
            .currentSceneBackStackEntry.collectAsState(null)
        val prevSceneEntry by navigator.stackManager
            .prevSceneBackStackEntry.collectAsState(null)

        BackHandler(canGoBack) {
            navigator.goBack()
        }

        currentSceneEntry?.let { sceneEntry ->
            val actualSwipeProperties = sceneEntry.swipeProperties ?: swipeProperties
            if (actualSwipeProperties == null) {
     Here ---->           AnimatedContent(sceneEntry, transitionSpec = transitionSpec) { entry ->
                    NavHostContent(composeStateHolder, entry)
                }
```

Any clues ? The implementation has no animations and is the default example shown on this repo

**Comment by gastsail** [comment]
Tried 1.5.0-beta01 and I get

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;
                                                                                                    	at androidx.compose.material.AnchoredDraggableState.<init>(AnchoredDraggable.kt:248)
                                                                                                    	at androidx.compose.material.DrawerState.<init>(Drawer.kt:124)
```

**Comment by Tlaster** [comment]
Which Compose-Multiplatform you're using for the project?

**Comment by gastsail** [comment]
Same, 1.5.0-beta01 and tried also 1.5.0-beta02 along with precompose beta01 and beta02, kotlin multiplatform plugin is 0.6.2

**Comment by gastsail** [comment]
Full log 

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;
                                                                                                    	at androidx.compose.material.AnchoredDraggableState.<init>(AnchoredDraggable.kt:248)
                                                                                                    	at androidx.compose.material.DrawerState.<init>(Drawer.kt:124)
                                                                                                    	at androidx.compose.material.DrawerKt$rememberDrawerState$2$1.invoke(Drawer.kt:457)
                                                                                                    	at androidx.compose.material.DrawerKt$rememberDrawerState$2$1.invoke(Drawer.kt:456)
                                                                                                    	at androidx.compose.runtime.saveable.RememberSaveableKt.rememberSaveable(RememberSaveable.kt:89)
                                                                                                    	at androidx.compose.material.DrawerKt.rememberDrawerState(Drawer.kt:456)
                                                                                                    	at androidx.compose.material.ScaffoldKt.rememberScaffoldState(Scaffold.kt:64)
                                                                                                    	at androidx.compose.material.ScaffoldKt.Scaffold-27mzLpw(Scaffold.kt:161)
                                                                                                    	at ComposableSingletons$AppKt$lambda-3$1.invoke(App.kt:35)
                                                                                                    	at ComposableSingletons$AppKt$lambda-3$1.invoke(App.kt:31)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at AppThemeKt$AppTheme$1.invoke(AppTheme.kt:19)
                                                                                                    	at AppThemeKt$AppTheme$1.invoke(AppTheme.kt:18)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:23)
                                                                                                    	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:82)
                                                                                                    	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:81)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:396)
                                                                                                    	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
                                                                                                    	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:72)
                                                                                                    	at AppThemeKt.AppTheme(AppTheme.kt:11)
                                                                                                    	at AppKt.App(App.kt:31)
                                                                                                    	at Main_androidKt.MainView(main.android.kt:6)
                                                                                                    	at com.myapplication.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:19)
                                                                                                    	at com.myapplication.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:17)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at moe.tlaster.precompose.lifecycle.PreComposeActivityKt$ContentInternal$1.invoke(PreComposeActivity.kt:99)
                                                                                                    	at moe.tlaster.precompose.lifecycle.PreComposeActivityKt$ContentInternal$1.invoke(PreComposeActivity.kt:98)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at moe.tlaster.precompose.lifecycle.PreComposeActivityKt$ProvideAndroidCompositionLocals$2.invoke(PreComposeActivity.kt:126)
                                                                                                    	at moe.tlaster.precompose.lifecycle.PreComposeActivityKt$ProvideAndroidCompositionLocals$2.invoke(PreComposeActivity.kt:125)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
2023-08-21 09:22:47.369 22671-22671 AndroidRuntime          com.myapplication.MyApplication      E  	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at moe.tlaster.precompose.lifecycle.PreComposeActivityKt.ProvideAndroidCompositionLocals(PreComposeActivity.kt:120)
                                                                                                    	at moe.tlaster.precompose.lifecycle.PreComposeActivityKt.ContentInternal(PreComposeActivity.kt:98)
                                                                                                    	at moe.tlaster.precompose.lifecycle.PreComposeActivityKt.access$ContentInternal(PreComposeActivity.kt:1)
                                                                                                    	at moe.tlaster.precompose.lifecycle.PreComposeActivityKt$setContent$2$1.invoke(PreComposeActivity.kt:73)
                                                                                                    	at moe.tlaster.precompose.lifecycle.PreComposeActivityKt$setContent$2$1.invoke(PreComposeActivity.kt:72)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:186)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:119)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:110)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:160)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:159)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:159)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:144)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3247)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3180)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:654)
                                                                                                    	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1041)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:562)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:144)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:135)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1220)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:135)
2023-08-21 09:22:47.369 22671-22671 AndroidRuntime          com.myapplication.MyApplication      E  	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:185)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:142)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:135)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1295)
                                                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:21290)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2820)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:832)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.runtime.PrimitiveSnapshotStateKt" on path: DexPathList[[zip file "/data/app/~~IDwhuXk5GHLjpi9Cn5paSw==/com.myapplication.MyApplication-wBraUFCVRtDCifLVV_1Qmw==/base.apk"],nativeLibraryDirectories=[/data/app/~~IDwhuXk5GHLjpi9Cn5paSw==/com.myapplication.MyApplication-wBraUFCVRtDCifLVV_1Qmw==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	... 112 more
```

**Comment by Tlaster** [comment]
Seems like you're using [accompanist version 0.33.0-alpha](https://github.com/gastsail/expenses-KMP/blob/7ea2b8ca13da2ff921859488ded7dfb0564a95f0/androidApp/build.gradle.kts#L13), which is targeting Compose 1.6, you can change it to [0.32.0](https://github.com/google/accompanist/releases/tag/v0.32.0) with PreCompose [1.5.0-rc01](https://github.com/Tlaster/PreCompose/releases/tag/1.5.0-rc01) and Compose-Multiplatform [1.5.0-rc01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.0-rc01)?

**Comment by Tlaster** [comment]
Yes, adding a library version compatible table might be a good idea, since the Compose library version management is still a disaster right now, we still need to manually check which version of Compose is supported for each library when writing apps.

**Comment by gastsail** [comment]
Thanks a lot @Tlaster
