### ISSUE TITLE
No Koin context has been provided

### ISSUE THREAD

**Issue by alorma** [Tlaster/PreCompose#185]
I'm receiving this error when trying to use the `precompose-koin` library.

```
Process: com.alorma.gasstations, PID: 21971
                 org.koin.compose.error.UnknownKoinContext: No Koin context has been provided
                 	at org.koin.compose.KoinApplicationKt$LocalKoinScope$1.invoke(KoinApplication.kt:49)
                 	at org.koin.compose.KoinApplicationKt$LocalKoinScope$1.invoke(KoinApplication.kt:48)
```

I initialize koin on the activity (or application, don't change the error) but trying to obtain the VM shows that error.

**Comment by alorma** [comment]
Solved, using KoinContext as root of all composables.
