### ISSUE TITLE
java.lang.NoSuchFieldError: $stable

### ISSUE THREAD

**Issue by sigmadeltasoftware** [Tlaster/PreCompose#2]
Hey man, appreciate the work behind Precompose and definitely think there's a future for it as it leans really close to Android indeed. 

I'm currently trying to implement the navigation for a Compose Desktop app, but I'm running into the following stacktrace as soon as the app launches and it draws the Home-page: 

```
> Task :desktop:run
Exception in thread "AWT-EventQueue-0 @coroutine#6" java.lang.NoSuchFieldError: $stable
	at moe.tlaster.precompose.navigation.transition.AnimatedRouteKt$AnimatedRoute$2$1.invoke(AnimatedRoute.kt:66)
	at moe.tlaster.precompose.navigation.transition.AnimatedRouteKt$AnimatedRoute$2$1.invoke(AnimatedRoute.kt:64)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at moe.tlaster.precompose.navigation.transition.AnimatedRouteKt.AnimatedRoute(AnimatedRoute.kt:94)
	at moe.tlaster.precompose.navigation.NavHostKt.NavHost(NavHost.kt:70)
	at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(NavHost.kt)
	at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(NavHost.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2162)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2405)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2586)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2579)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotState.kt:540)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2572)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:2548)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:612)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:764)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:103)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:447)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:416)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.platform.DesktopOwners.onFrame(DesktopOwners.desktop.kt:125)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:147)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.kt:314)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.update(MetalRedrawer.kt:57)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.access$update(MetalRedrawer.kt:17)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invokeSuspend(MetalRedrawer.kt:29)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:36)
	(Coroutine boundary)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt:416)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2$2.invokeSuspend(Recomposer.kt:673)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2.invokeSuspend(Recomposer.kt:672)
	at androidx.compose.ui.platform.DesktopOwners$2.invokeSuspend(DesktopOwners.desktop.kt:82)
	(Coroutine creation stacktrace)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:184)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at androidx.compose.ui.platform.DesktopOwners.<init>(DesktopOwners.desktop.kt:81)
	at androidx.compose.ui.awt.ComposeLayer.<init>(ComposeLayer.desktop.kt:68)
	at androidx.compose.ui.awt.ComposeWindowDelegate.<init>(ComposeWindowDelegate.desktop.kt:37)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:36)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.desktop.kt:131)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.desktop.kt)
	at androidx.compose.desktop.AppWindow_desktopKt$Window$1.run(AppWindow.desktop.kt:95)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoSuchFieldError: $stable
	at moe.tlaster.precompose.navigation.transition.AnimatedRouteKt$AnimatedRoute$2$1.invoke(AnimatedRoute.kt:66)
	at moe.tlaster.precompose.navigation.transition.AnimatedRouteKt$AnimatedRoute$2$1.invoke(AnimatedRoute.kt:64)
Caused by: java.lang.NoSuchFieldError: $stable

	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at moe.tlaster.precompose.navigation.transition.AnimatedRouteKt.AnimatedRoute(AnimatedRoute.kt:94)
	at moe.tlaster.precompose.navigation.NavHostKt.NavHost(NavHost.kt:70)
	at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(NavHost.kt)
	at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(NavHost.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2162)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2405)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2586)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2579)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotState.kt:540)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2572)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:2548)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:612)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:764)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:103)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:447)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:416)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.platform.DesktopOwners.onFrame(DesktopOwners.desktop.kt:125)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:147)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.kt:314)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.update(MetalRedrawer.kt:57)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.access$update(MetalRedrawer.kt:17)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invokeSuspend(MetalRedrawer.kt:29)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:36)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 13 more
```

I'm currently trying to reproduce my Android app in a separate repository for a Desktop app as there are currently too many version-misalignment issues to get both running well in the same project. And as soon as it has built the `Scaffold` that contains the `NavHost`, it seems to throw this stacktrace.

Would you by any chance know what the issue could be?

**Comment by Tlaster** [comment]
Sorry for the late reply, I've been busy for the last week, could you provide a reproducible example for this issue?
