### ISSUE TITLE
[BUG] java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Object;Ljava/lang/Object;)V in class Landroidx/compose/animation/core/SeekableTransitionState;

### ISSUE THREAD

**Issue by FunkyMuse** [Tlaster/PreCompose#349]
**Describe the bug**
When going back from a destination the app crashes with 

**To Reproduce**
Use Compose multiplatform 1.7.X-alpha or dev
navigate from a destination, go back
crash, not always

**Expected behavior**
User should be returned to the destination safely

**Minimal reproducible example**
I guess that's something introduced in 1.7.X Compose multiplatform that breaks the library

stack trace is

```
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Object;Ljava/lang/Object;)V in class Landroidx/compose/animation/core/SeekableTransitionState; or its super classes (declaration of 'androidx.compose.animation.core.SeekableTransitionState' appears in /data/app/~~49ENzoh7ld7afOHMt_9WzA==/com.x.x.debug-AIZoxjVS9E177qpLp0l5xQ==/base.apk)
                                                                                                    	at moe.tlaster.precompose.navigation.NavHostKt$NavHost$6.invoke(NavHost.kt:191)
                                                                                                    	at moe.tlaster.precompose.navigation.NavHostKt$NavHost$6.invoke(NavHost.kt:140)
```

**Comment by Tlaster** [comment]
Yes compose 1.7.x change the SeekableTransitionState's API, which I will update to use the new version after 1.7.x has been released.

**Comment by FunkyMuse** [comment]
> Yes compose 1.7.x change the SeekableTransitionState's API, which I will update to use the new version after 1.7.x has been released.

1.7.X is in alpha now, maybe a PreCompose alpha/beta release too?

**Comment by emirhanemmez** [comment]
it would be great if you fix that bug :) thanks for your effort

**Comment by mobiletoly** [comment]
any news on having it fixed? and thank you for a great library!

**Comment by Tlaster** [comment]
PreCompose 1.7.0-alpha01 is out with compose multiplatform 1.7.0-beta02 support, which should resolve the issue.

**Comment by mobiletoly** [comment]
I saw that precompose 1.7.0-alpha02 was released, but after adding it - I'm getting error:

```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':composeApp:transformNativeMainCInteropDependenciesMetadataForIde'.
> Could not resolve all files for configuration ':composeApp:nativeMainResolvableDependenciesMetadata'.
   > Could not find moe.tlaster:precompose-viewmodel:1.7.0-alpha02.
     Required by:
         project :composeApp
   > Could not find moe.tlaster:precompose-koin:1.7.0-alpha02.
     Required by:
         project :composeApp
```

I don't have the same issue is with 1.7.0-alpha01

**Comment by Tlaster** [comment]
> I saw that precompose 1.7.0-alpha02 was released, but after adding it - I'm getting error:
> 
> ```
> 1: Task failed with an exception.
> -----------
> * What went wrong:
> Execution failed for task ':composeApp:transformNativeMainCInteropDependenciesMetadataForIde'.
> > Could not resolve all files for configuration ':composeApp:nativeMainResolvableDependenciesMetadata'.
>    > Could not find moe.tlaster:precompose-viewmodel:1.7.0-alpha02.
>      Required by:
>          project :composeApp
>    > Could not find moe.tlaster:precompose-koin:1.7.0-alpha02.
>      Required by:
>          project :composeApp
> ```
> 
> I don't have the same issue is with 1.7.0-alpha01

`moe.tlaster:precompose-viewmodel` is no longer used and replaced by `org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose`, this is a major change for 1.7.0-alpha02, you can still keep 1.7.0-alpha01 if you're not ready to migrate to Jetpack's ViewModel.
https://github.com/Tlaster/PreCompose/releases/tag/1.7.0-alpha02

**Comment by mobiletoly** [comment]
oh OK, thank you. luckily for me migration should be pretty straightforward, especially because I recently discovered that PreCompose/Molecule is in most cases better choice for me than using ViewModel approach.

**Comment by misskbar** [comment]
Any updates with this issue?

**Comment by andrearossini-bf** [comment]
Yes actually it works, mine was just some other plugins' conflict. I suggest to verify carefully all plugins' compatibility, eventually disabling and reintegrating them gradually.
