### ISSUE TITLE
App Crash on Long NavTransition

### ISSUE THREAD

**Issue by VerushkinRoman** [Tlaster/PreCompose#39]
When nav transition's duration lasts too long and during transition i try to navigate one more time to same destination, i get crush:

```
java.lang.IllegalArgumentException: Key 1-Login was used multiple times 
    at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:89)
    at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:88)
    at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
    at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1105)
    at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:820)
    at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:842)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:592)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
    at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
    at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
    at android.view.Choreographer.doCallbacks(Choreographer.java:899)
    at android.view.Choreographer.doFrame(Choreographer.java:827)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7884)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@d547794, androidx.compose.ui.platform.MotionDurationScaleImpl@9de323d, StandaloneCoroutine{Cancelling}@f182a32, AndroidUiDispatcher@ed16383]
```

**Comment by Tlaster** [comment]
Seem like navigate to the same page at the same time. I'll try to fix it.

**Comment by VerushkinRoman** [comment]
After updating to 1.5.0 and 1.5.1 still same issue came back.

`java.lang.IllegalArgumentException: Key 1-BalanceFlow was used multiple times 
    androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:89)
    androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:88)
    androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
    androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1137)
    androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
    androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
    androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:625)
    androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
    androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
    androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.java:109)
    androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.java:41)
    androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
    android.view.Choreographer$CallbackRecord.run(Choreographer.java:1449)
    android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
    android.view.Choreographer.doCallbacks(Choreographer.java:1089)
    android.view.Choreographer.doFrame(Choreographer.java:998)
    android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
    android.os.Handler.handleCallback(Handler.java:942)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loopOnce(Looper.java:210)
    android.os.Looper.loop(Looper.java:299)
    android.app.ActivityThread.main(ActivityThread.java:8261)
    java.lang.reflect.Method.invoke(Method.java:0)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
`

**Comment by Tlaster** [comment]
Seems like #42 did not resolve the issue, reopen and I'll check it.
