### ISSUE TITLE
[BUG] Exception in thread "main" java.lang.IllegalStateException: No Window for PreCompose, please use ProvidePreComposeLocals in WindowScope to setup your desktop project

### ISSUE THREAD

**Issue by JagadishaIncture** [Tlaster/PreCompose#408]
Exception in thread "main" java.lang.IllegalStateException: No Window for PreCompose, please use ProvidePreComposeLocals in WindowScope to setup your desktop project

Below error while running in desktop
<img width="958" alt="Screenshot 2024-11-28 at 6 50 50 PM" src="https://github.com/user-attachments/assets/4fbc4f91-7c60-411e-8c2f-5952b33c30b4">
 

Config

CMP : 1.6.11
Kotlin 2.0.0
Precompose 1.6.2

**Comment by JagadishaIncture** [comment]
Exception in thread "main" java.lang.IllegalStateException: No Window for PreCompose, please use ProvidePreComposeLocals in WindowScope to setup your desktop project
	at moe.tlaster.precompose.PreComposeWindowKt.LocalWindow$lambda$1(PreComposeWindow.kt:78)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:46)
	at androidx.compose.runtime.LazyValueHolder.readValue(ValueHolders.kt:48)
	at androidx.compose.runtime.CompositionLocalMapKt.read(CompositionLocalMap.kt:91)
	at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:2375)
	at moe.tlaster.precompose.PreComposeWindowKt.PreComposeApp(PreComposeWindow.kt:162)

**Comment by Yanguan619** [comment]
```kotlin
fun main() = application {
    Window(
        onCloseRequest = ::exitApplication,
        title = "",
    ) {
        ProvidePreComposeLocals {
            App()
        }
    }
}
```

**Comment by Yanguan619** [comment]
> Exception in thread "main" java.lang.IllegalStateException: No Window for PreCompose, please use ProvidePreComposeLocals in WindowScope to setup your desktop project
> 
> Below error while running in desktop <img alt="Screenshot 2024-11-28 at 6 50 50 PM" width="958" src="https://private-user-images.githubusercontent.com/55983819/390798409-4fbc4f91-7c60-411e-8c2f-5952b33c30b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MDA3NDMsIm5iZiI6MTczNTQwMDQ0MywicGF0aCI6Ii81NTk4MzgxOS8zOTA3OTg0MDktNGZiYzRmOTEtN2M2MC00MTFlLThjMmYtNTk1MmIzM2MzMGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDE1NDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzOWQwNzQ1YjE2ZjAzZWQzNzk5OWYzODhlZmM3NTA3NTA3OWMzNDI2ZTU3ZWY5ZTRhMjQxNTU5ZjVlY2FjNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zH_J6OcUQXkx00Iwa0GPV-fWyOqLrLeSPXyNisGF7Pc">
> 
> Config
> 
> CMP : 1.6.11 Kotlin 2.0.0 Precompose 1.6.2

exmple for jvmMain:
```kotlin
fun main() = application {
    Window(
        onCloseRequest = ::exitApplication,
        title = "",
    ) {
        ProvidePreComposeLocals {
            App()
        }
    }
}
```

**Comment by bennysway** [comment]
The solution proposed by @Yanguan619 fixes the issue. I propose we close it? 😊
