### ISSUE TITLE
Can't use with compose-multiplatform 1.5.0-beta01

### ISSUE THREAD

**Issue by RomanTsarou** [Tlaster/PreCompose#77]
When I use version 1.4.3 with compose-multiplatform 1.5.0-beta01, I get the error:
`
FATAL EXCEPTION: main
Process: super.kmmapp.debug, PID: 2689
java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Ljava/lang/String;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~qom9S0eNzgnq3MigV5v-2w==/super.kmmapp.debug-jmAIptZSvKgBufIuH3j_4w==/base.apk)
at moe.tlaster.precompose.navigation.NavHostKt.NavHost(NavHost.kt:135)
at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(Unknown Source:23)
at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(Unknown Source:10)
at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2468)
at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2737)
at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3352)
at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3303)
at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:781)
at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1097)
at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:569)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
at android.view.Choreographer.doCallbacks(Choreographer.java:899)
at android.view.Choreographer.doFrame(Choreographer.java:827)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
`

**Comment by sphrak** [comment]
I see this as well

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 'void androidx.compose.animation.AnimatedContentKt.AnimatedContent(java.lang.Object, androidx.compose.ui.Modifier, kotlin.jvm.functions.Function1, androidx.compose.ui.Alignment, java.lang.String, kotlin.jvm.functions.Function4, androidx.compose.runtime.Composer, int, int)'
        at moe.tlaster.precompose.navigation.NavHostKt.NavHost(NavHost.kt:135)
        at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(NavHost.kt)
        at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(NavHost.kt)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2469)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2738)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3353)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:3304)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:781)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1097)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:569)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
        at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
        at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
        at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:451)
        at androidx.compose.ui.awt.ComposeBridge$skikoView$1$onRender$1.invoke(ComposeBridge.desktop.kt:153)
        at androidx.compose.ui.awt.ComposeBridge$skikoView$1$onRender$1.invoke(ComposeBridge.desktop.kt:152)
        at androidx.compose.ui.awt.ComposeBridge.catchExceptions(ComposeBridge.desktop.kt:126)
        at androidx.compose.ui.awt.ComposeBridge.access$catchExceptions(ComposeBridge.desktop.kt:59)
        at androidx.compose.ui.awt.ComposeBridge$skikoView$1.onRender(ComposeBridge.desktop.kt:152)
        at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:548)
        at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
        at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invokeSuspend(MetalRedrawer.kt:83)
        at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
        at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
        at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeBridge$coroutineExceptionHandler$1@676449d1, androidx.compose.runtime.BroadcastFrameClock@60547b90, StandaloneCoroutine{Cancelling}@166df664, FlushCoroutineDispatcher@73dcc24c]
```

**Comment by devbasil** [comment]
> RomanTsarou

@RomanTsarou and @sphrak  Have you tried the temporary fix suggested by @qdsfdhvh at issue #73 , I've tested it and it works, you may close this issue if the temporary fix works for you. Good luck.

`maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")

implementation("io.github.qdsfdhvh:precompose:1.4.5-SNAPSHOT")`

**Comment by Tlaster** [comment]
I'm still trying to upgrade to Compose 1.5.0, but like #76 and #74 ,1.5.0 breaks the build and I'm still working on it.

**Comment by Tlaster** [comment]
There's a new release [1.5.0-beta01](https://github.com/Tlaster/PreCompose/releases/tag/1.5.0-beta01) you can try it out.

**Comment by sphrak** [comment]
Sweet it works wonders, thanks for such swift action 💯 🚀
