### ISSUE TITLE
Compose 1.5.0-beta01

### ISSUE THREAD

**Issue by heiha100** [Tlaster/PreCompose#85]
encounter a problem after upgrage compose to 1.5.0-beta01
```
java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Ljava/lang/String;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~KrOEfD1jb4WZLVRIa5rbsg==/com.sr01.www.qiaqia-oiP2ujbbQD42k5TiOcTqZA==/base.apk)
     at moe.tlaster.precompose.navigation.NavHostKt.NavHost(NavHost.kt:135)
     at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(Unknown Source:23)
     at moe.tlaster.precompose.navigation.NavHostKt$NavHost$5.invoke(Unknown Source:10)
     at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
     at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2468)
     at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2737)
     at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3352)
     at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3303)
     at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:781)
     at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1097)
     at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
     at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:569)
     at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
     at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
     at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
     at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
     at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1230)
     at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
     at android.view.Choreographer.doFrame(Choreographer.java:925)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
     at android.os.Handler.handleCallback(Handler.java:938)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loopOnce(Looper.java:233)
     at android.os.Looper.loop(Looper.java:344)
     at android.app.ActivityThread.main(ActivityThread.java:8212)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Comment by Tlaster** [comment]
Have you try PreCompose [1.5.0-beta01](https://github.com/Tlaster/PreCompose/releases/tag/1.5.0-beta01)?

**Comment by heiha100** [comment]
After upgrade PreCompose to 1.5.0-beta01, the issues has been resolved. Tank you for your job.

**Comment by Tlaster** [comment]
close as resolved
